#!/bin/sh
set -e
package_name=xterm-hide
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/debian-uxterm.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/debian-xterm.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/debian-uxterm.desktop"
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/debian-xterm.desktop"
;;
esac
exit 0
